// This file will be auto-generated by kysely-codegen
// Run: npm run db:types

import type { ColumnType } from 'kysely'

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Tenants {
  id: Generated<string>
  name: string
  slug: string
  session_timeout_minutes: Generated<number | null>
  welcome_message_known: string | null
  welcome_message_new: string | null
  default_flow_id: string | null
  timezone: Generated<string | null>
  created_at: Generated<Timestamp>
  updated_at: Generated<Timestamp>
  deleted_at: Timestamp | null
}

export interface WhatsappAccounts {
  id: Generated<string>
  tenant_id: string
  phone_number: string
  phone_number_id: string
  business_account_id: string
  access_token: string
  webhook_verify_token: string
  status: Generated<string | null>
  created_at: Generated<Timestamp>
  updated_at: Generated<Timestamp>
  deleted_at: Timestamp | null
}

export interface Users {
  id: Generated<string>
  tenant_id: string
  phone_number: string
  name: string | null
  email: string | null
  metadata: Generated<Record<string, any>>
  created_at: Generated<Timestamp>
  updated_at: Generated<Timestamp>
  deleted_at: Timestamp | null
}

export interface Flows {
  id: Generated<string>
  tenant_id: string
  whatsapp_account_id: string | null
  name: string
  description: string | null
  trigger_type: string
  trigger_keywords: string[] | null
  is_default: Generated<boolean | null>
  is_active: Generated<boolean | null>
  created_at: Generated<Timestamp>
  updated_at: Generated<Timestamp>
  deleted_at: Timestamp | null
}

export interface FlowNodes {
  id: Generated<string>
  flow_id: string
  parent_node_id: string | null
  node_type: string
  config: Record<string, any>
  position: Record<string, any> | null
  transitions: Record<string, any> | null
  created_at: Generated<Timestamp>
  updated_at: Generated<Timestamp>
}

export interface Conversations {
  id: Generated<string>
  tenant_id: string
  whatsapp_account_id: string
  user_id: string
  active_flow_id: string | null
  current_node_id: string | null
  context: Generated<Record<string, any>>
  session_expires_at: Timestamp | null
  status: Generated<string | null>
  created_at: Generated<Timestamp>
  updated_at: Generated<Timestamp>
  deleted_at: Timestamp | null
}

export interface Messages {
  id: Generated<string>
  conversation_id: string
  tenant_id: string
  whatsapp_message_id: string | null
  direction: string
  type: string
  content: Record<string, any>
  status: string | null
  content_text: string | null
  sent_at: Generated<Timestamp>
  deleted_at: Timestamp | null
}

export interface WebhookLogs {
  id: Generated<string>
  tenant_id: string | null
  method: string
  headers: Record<string, any> | null
  body: Record<string, any> | null
  response_status: number | null
  error: string | null
  created_at: Generated<Timestamp>
}

export interface Database {
  tenants: Tenants
  whatsapp_accounts: WhatsappAccounts
  users: Users
  flows: Flows
  flow_nodes: FlowNodes
  conversations: Conversations
  messages: Messages
  webhook_logs: WebhookLogs
}
